server:
    port: 8080
    servlet:
        context-path: /flobank
spring:
    application:
        name: flobank_api

    # ✅ 1. DB 접속 정보
    datasource:
      url: jdbc:oracle:thin:@34.22.80.47:1521/XEPDB1
      username: flobank
      password: 1234
      driver-class-name: oracle.jdbc.OracleDriver

    mail:
      host: smtp.gmail.com
      port: 587
      username: alswnstl23@gmail.com
      password: nkel ifue pjnh hzyj
      properties:
        mail:
          smtp:
            auth: true
            timeout: 5000
            starttls:
              enable: true
            ssl:
              trust: smtp.gmail.com


flobank:
  ap: # 접속해야 할 flobank_ap (AP 서버) 정보
    host: 34.22.80.47
    port: 9090 # AP 서버와 약속한 TCP 포트
  aes:
    secret: "01234567890123456789012345678901"

# ✅ 2. MyBatis 설정
mybatis:
  # SQL 쿼리가 작성될 XML 매퍼 파일의 위치를 지정
  mapper-locations: classpath:mappers/**/*.xml
  # DB의 snake_case 컬럼(ex: exchange_rate)을
  # Java의 camelCase 프로퍼티(ex: exchangeRate)로 자동 매핑
  configuration:
    map-underscore-to-camel-case: true

jwt:
  secret: "v3rySecr3tKeyF0rFl0BankApiProjectMustBeLongerThan256Bits!!" # 256비트 이상 길이 필수

eximbank:
  api:
    base-url: "https://oapi.koreaexim.go.kr/site/program/financial/exchangeJSON"
    auth-key: "LNyeb6x2OFLu289XSY1tokxFueROPpxI"   # API Key

openai:
  api-key: ${OPENAI_API_KEY}
  base-url: "https://api.openai.com/v1"

#휴대폰 인증
solapi:
  apiKey: NCSGTLVVAFB7GAHV
  apiSecret: N7V7FAHACZ8KWKNQPQFUCGSDSWWL4K5E
  phoneNumber: 01021098237


#############################################
  # 지울예정
terms:
  base-dir : C:/Users/GGG/Desktop/workspace
#############################################